version: '3'

services:
  redis:
    image: redis:6.0
    container_name: gobarber_cache
    ports:
      - 6379:6379
    networks:
      - app-network

  postgres:
    image: postgres:12
    container_name: gobarber_postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
    volumes:
      - dbdata:/data/db
    ports:
      - 5432:5432
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: gobarber_mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - app-network

  nodejs:
    image: node:12.18-alpine
    container_name: gobarber_backend
    restart: unless-stopped
    build: .
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - redis
      - postgres
      - mongo
    environment:
      - REDIS_URL=redis://gobarber_cache
      - NODE_ENV=development
      - PORT=3333
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  mongodb:
